// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "d515e16f-b1f9-4d19-a5bb-adf85612027b");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1650652505);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1650652504);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{2ee56481-1c0f-484c-9a11-3336a324bb4c}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1650652502);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 125);
user_pref("browser.newtabpage.activity-stream.impressionId", "{7385aaa4-a6cb-412e-a2db-0bfd533fa9d1}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1650652504);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1650652505779");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1650674105779");
user_pref("browser.search.region", "US");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1650652503");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20220422105613");
user_pref("browser.startup.homepage_override.mstone", "100.0");
user_pref("browser.startup.homepage_override.once", "{\"message_id\":\"WNP_MOMENTS_13\",\"url\":\"https://www.mozilla.org/firefox/welcome/13\",\"expire\":1640908800000}");
user_pref("browser.startup.lastColdStartupCheck", 1650652504);
user_pref("browser.theme.content-theme", 0);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"developer-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\",\"profiler-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "offline");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1650652504223");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "100.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "US");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "ca3c7777c396494fbc76f221443e3420");
user_pref("extensions.activeThemeID", "firefox-compact-dark@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20220422105613");
user_pref("extensions.lastAppVersion", "100.0");
user_pref("extensions.lastPlatformVersion", "100.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"4bc161a8-bf9c-4230-b070-da5917e79688\",\"formautofill@mozilla.org\":\"f7667919-a2e6-4362-a935-7cc4b583c7fc\",\"pictureinpicture@mozilla.org\":\"075205dc-b8a4-446f-b193-24e56cd3d901\",\"screenshots@mozilla.org\":\"adcdbae5-df89-488d-80c0-a6f6213c7b03\",\"webcompat-reporter@mozilla.org\":\"a8599022-bef4-419c-a534-2d76ccf5595f\",\"webcompat@mozilla.org\":\"61d104bc-fa0b-41a3-97d4-d7ae5af6d498\",\"addons-search-detection@mozilla.com\":\"20583b45-3a27-41e8-a625-fbd1878e8110\",\"google@search.mozilla.org\":\"34d0350f-309c-4a75-88a7-e85d89dd5a12\",\"amazondotcom@search.mozilla.org\":\"260afca1-7b89-4a50-88aa-10705e48d0de\",\"wikipedia@search.mozilla.org\":\"49ccde84-ef7f-46f3-a229-d413eecb280e\",\"bing@search.mozilla.org\":\"65debcde-884a-4d56-b869-ecaf9c7e9a52\",\"ddg@search.mozilla.org\":\"c9f0bd0c-7ba9-465d-95c6-2b3d82ed0e98\",\"firefox-compact-dark@mozilla.org\":\"80d8655d-032a-4c9d-af66-3abfb795a90f\",\"ebay@search.mozilla.org\":\"9ab2a46c-2ebf-4258-8628-342430c90dcd\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1650652504);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "b98972c0-a264-47e0-9328-0bee3e6c5ef5");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.telemetry.cachedClientID", "8b8d2cf7-f9c2-4424-941a-645e5dcca922");
user_pref("toolkit.telemetry.previousBuildID", "20220422105613");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
